### ISSUE TITLE
Cuda not working 

### ISSUE THREAD

**Issue by mattiasstahre** [talipucar/PyFlow_CPC#1]
Getting "RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at CPU" when trying to use GPU.

**Comment by talipucar** [comment]
Could you please share the error? Where does it occur?

**Comment by mattiasstahre** [comment]
Hi, thanks for responding.

```
Traceback (most recent call last):
  File "0_train.py", line 72, in <module>
    main(config)
  File "0_train.py", line 53, in main
    train(config, data_loader, save_weights=True)
  File "0_train.py", line 29, in train
    encoder.fit(data_loader)
  File "/home/mattias/PyFlow_CPC/src/model.py", line 103, in fit
    encoder_samples, predictions, hidden = self.cpc(Xbatch, hidden)
  File "/home/mattias/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mattias/PyFlow_CPC/utils/model_utils.py", line 60, in forward
    output, hidden = self.gru(prior_sequence, hidden)
  File "/home/mattias/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mattias/anaconda3/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 837, in forward
    result = _VF.gru(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu
```

**Comment by talipucar** [comment]
OK, I think, you need to move **hidden** variable generated at **line 101** of **src/model.py** to the device by using **self.device**.

For example:

```
hidden = th.zeros(2, bs, self.options["conv_dims"][-1])
hidden = hidden.to(self.device)
```

OR you can edit line 101 as following:

`hidden = th.zeros((2, bs, self.options["conv_dims"][-1]), device=self.device)
`

So, either way should work. Please try, and see if it works. And if it does, please let me know.

**Comment by mattiasstahre** [comment]
Getting the same error on this line:
```
 File "/home/mattias/PyFlow_CPC/src/model.py", line 103, in fit
    encoder_samples, predictions, hidden = self.cpc(Xbatch, hidden)
```

**Comment by mattiasstahre** [comment]
Getting further now but an error at:

```
Traceback (most recent call last):
  File "0_train.py", line 72, in <module>
    main(config)
  File "0_train.py", line 53, in main
    train(config, data_loader, save_weights=True)
  File "0_train.py", line 29, in train
    encoder.fit(data_loader)
  File "/home/mattias/PyFlow_CPC/src/model.py", line 122, in fit
    _ = self.validate(Xval) if epoch % self.options["nth_epoch"] == 0 else None
  File "/home/mattias/PyFlow_CPC/src/model.py", line 189, in validate
    encoder_samples, predictions, hidden = self.cpc(Xval, hidden)
  File "/home/mattias/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mattias/PyFlow_CPC/utils/model_utils.py", line 60, in forward
    output, hidden = self.gru(prior_sequence, hidden)
  File "/home/mattias/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mattias/anaconda3/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 837, in forward
    result = _VF.gru(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu
```

**Comment by talipucar** [comment]
You have to do the same thing at line 187.

```
            # S=num_layers*num_directions, i.e. 2*1 since we are using 2 layers, and GRU is set as uni-directional
            hidden = th.zeros(2, self.options["batch_size"], self.options["conv_dims"][-1])
```

**Comment by mattiasstahre** [comment]
Worked great now! Thanks for the input.

**Comment by talipucar** [comment]
Great! I will update the source code sometime soon. 

Just a side note, in line 43 of `./utils/load_data.py`, test_dataset is commented out. 

If you want to use the test data, download  "dev-clean" from original source where you downloaded the training set, and uncomment line 43. In this case, you need to change line 45 from `return train_dataset, train_dataset` to `return train_dataset, test_dataset`

I am closing this issue.
